/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import org.junit.Test;

public class ClientAppTest {
  @Test public void testAppHasAGreeting() {
    // ClientApp classUnderTest = new ClientApp();
    // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    // 우리가 당장 이 테스트 기능을 사용할 게 아니기 때문에 주석 막아 준다.
  }
}
